name: CG server

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            DIR="/home/ec2-user/server"
            #npx pm2 delete all
            cd /home/ec2-user
            
            if [ ! -d $DIR ]
            then
              mkdir server &&
              git clone https://github.com/Prathm98/cg-blog-server.git server &&
              cd server &&
              npm i
              npx tsc
            else
              cd server
            fi
            
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            pm2 start build/index.js
          '
            